pipeline {
    agent any

    tools {
        jdk 'JDK-17'
        maven 'Maven-3-9'
    }

    environment {
        APP_NAME = "springboot-demo"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Stage 1: Checkout from GitHub"
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Stage 2: Compile Application"
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                echo "Stage 3: Run Unit Tests"
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                echo "Stage 4: Package Application"
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Verify Artifact') {
            steps {
                echo "Stage 5: Verify JAR file"
                sh 'ls -l target/'
            }
        }
    }

    post {
        success {
            echo "Pipeline Completed Successfully 🎉"
        }
        failure {
            echo "Pipeline Failed ❌"
        }
        always {
            echo "Build Finished."
        }
    }
}
